### ISSUE TITLE
Backend Implementation

### ISSUE THREAD

**Issue by TheVoidLives** [KalonteJT/COP-4331-Group-14#11]
The backend should provide the following functionality in order to support the front-end applications.

* A Database 
    - [x] Setup MLAB instance of MongoDB
    - [x] Populate 
    - [x] Store Users (username/password)
    - [x] Store Events (name/time)
    - [ ] Determine data policy. Do we save past events? Do we drop them from our history? Do we track the events a user was a part of?
* A RESTful API (webservice)
    - [ ] Provide basic user authentication
    - [x] Provide REST API endpoints to request DB Info
    - [x] Perform DB Queries and pass data to clients
* Business layer
    - [x] Standardize DB datamodel

**Comment by TheVoidLives** [comment]
Link #14 as some of this work may be tracked there.

**Comment by TheVoidLives** [comment]
#3 Currently covered by Trevor. Update as necessary.

**Comment by TheVoidLives** [comment]
API is functional. Closed #9.  Deploying to AWS in #22. 
@trevortosi Will work with you on finalizing Auth0 so that is solid no later than this weekend. 

@KalonteJT @Silveresque @crussell122  Will get with you all, and I guess everyone, once the API is deployed. The request are simple JSON to and from the API so it should be super easy.
